export const environment = {
  registerUrl: 'http://localhost:8080/api/users/register',
  loginUrl: 'http://localhost:8080/api/users/login',
  validateToken: 'http://localhost:8080/api/users/validate-token',
  getStudents: 'http://localhost:8080/api/students/get-all',
  getStudentById: 'http://localhost:8080/api/students/get/',
  createStudent: 'http://localhost:8080/api/students/create',
  updateStudent: 'http://localhost:8080/api/students/update/',
  deleteStudent: 'http://localhost:8080/api/students/delete/',
  getBooks: 'http://localhost:8080/api/books/get-all',
  getBookById: 'http://localhost:8080/api/books/get/',
  createBook: 'http://localhost:8080/api/books/create',
  deleteBook: 'http://localhost:8080/api/books/delete/',
  updateBook: 'http://localhost:8080/api/books/update/',
  getLoans: 'http://localhost:8080/api/loans/get-all',
  getInfoLoans: 'http://localhost:8080/api/loans/get-info-loans',
  createLoan: 'http://localhost:8080/api/loans/create',
  updateLoan: 'http://localhost:8080/api/loans/update/',
  returnLoan: 'http://localhost:8080/api/loans/return-book/'
};
